services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8088:8000"
    environment:
      - CHROMA_DATABASE_DIR=/data
    volumes:
      - ./chroma_db:/data

  rag_app:
    build: .
    container_name: rag_streamlit
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - chromadb
    volumes:
      - ./images:/app/images
